image: mono:latest

stages:
    - test
    - build

before_script:
    - apt-get -qq update
    - apt-get -yqq install git
    - apt-get -yqq install wget
    - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - mono nuget.exe restore -NonInteractive

cache:
  paths:
  - .veronique/

release:
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - Veronique.exe
          - LICENSE.md
          - USAGE.md
          - CHANGELOG.md
          - AUTHORS.txt
          - ./*.nupkg
    script:
        - mono packages/Veronique.0.9.0/tools/Veronique.exe
        - msbuild "Veronique.sln" /p:Configuration="Release" /p:Platform="Any CPU"
        - cp Build/Release/Veronique.exe Veronique.exe
        - mono nuget.exe pack Veronique.nuspec
        - mono nuget.exe push Veronique*.nupkg $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json

ci-release:
    stage: build
    only:
        - master
    except:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 4 weeks
        paths:
          - Veronique.exe
          - LICENSE.md
          - USAGE.md
          - CHANGELOG.md
          - AUTHORS.txt
          - ./*.nupkg
    script:
        - mono packages/Veronique.0.9.0/tools/Veronique.exe
        - msbuild "Veronique.sln" /p:Configuration="Release" /p:Platform="Any CPU"
        - cp Build/Release/Veronique.exe Veronique.exe
        - mono nuget.exe pack Veronique.nuspec
    
ci-debug:
    stage: test
    script:
        - msbuild "Veronique.sln" /p:Configuration="Debug" /p:Platform="Any CPU"
        - mono packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe Build/Debug/Veronique.Test.dll --work=Build/Debug/ --result=Veronique.TestReport.xml