image: mono:latest

stages:
    - build
    - test

before_script:     
    - nuget restore -NonInteractive

release:
    stage: build
    only:
        - tags
    artifacts:
        name: "Veronique-${CI_COMMIT_TAG}"
        paths:
          - Veronique.exe
          - LICENSE.md
          - USAGE.md
          - CHANGELOG.md
          - AUTHORS.txt
    script:
        - xbuild "Veronique.sln" /p:Configuration="Release" /p:Platform="Any CPU"
        - cp Build/Release/Veronique.exe Veronique.exe

ci-release:
    stage: build
    only:
        - master
    except:
        - tags
    artifacts:
        name: "Veronique-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 4 weeks
        paths:
          - Veronique.exe
          - LICENSE.md
          - USAGE.md
          - CHANGELOG.md
          - AUTHORS.txt
    script:
        - xbuild "Veronique.sln" /p:Configuration="Release" /p:Platform="Any CPU"
        - cp Build/Release/Veronique.exe Veronique.exe
    
ci-debug:
    stage: test
    artifacts:
        name: "Veronique-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 1 week
        paths:
          - Build/Debug/Veronique.Test.dll
          - Build/Debug/Veronique.exe
          - Build/Debug/Veronique.TestReport.xml
    script:
        - xbuild "Veronique.sln" /p:Configuration="Debug" /p:Platform="Any CPU"
        - mono packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe Build/Debug/Veronique.Test.dll --work=Build/Debug/ --result=Veronique.TestReport.xml